[package]
name = "bench_riddle"
version = "0.1.0"
edition = "2021"

[dependencies]
jemallocator = "0.5.4"
rustc-hash = "1.1.0"

[dev-dependencies]
binggan = "0.8.0"

[[bench]]
name = "bench_riddle"
harness = false

